config/routes.rb
Rails.application.routes.draw do
  resources :movies

  resources :videoformats

  resources :ratings

  get 'welcome/home'

   root 'welcome#home'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  belongs_to :rating
  belongs_to :videoformat

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  has_many :movies

end

app/models/videoformat.rb
class Videoformat < ActiveRecord::Base
  has_many :movies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @search = Movie.search(params[:f])
    @movies = @search.result
    @movie = Movie.order(params[:sort])
    @movies = Movie.order(:title).page(params[:page]).per(5)
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :length, :release, :videoformat_id, :rating_id)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:rate)
    end
end

app/controllers/videoformats_controller.rb
class VideoformatsController < ApplicationController
  before_action :set_videoformat, only: [:show, :edit, :update, :destroy]

  # GET /videoformats
  # GET /videoformats.json
  def index
    @videoformats = Videoformat.all
  end

  # GET /videoformats/1
  # GET /videoformats/1.json
  def show
  end

  # GET /videoformats/new
  def new
    @videoformat = Videoformat.new
  end

  # GET /videoformats/1/edit
  def edit
  end

  # POST /videoformats
  # POST /videoformats.json
  def create
    @videoformat = Videoformat.new(videoformat_params)

    respond_to do |format|
      if @videoformat.save
        format.html { redirect_to @videoformat, notice: 'Videoformat was successfully created.' }
        format.json { render :show, status: :created, location: @videoformat }
      else
        format.html { render :new }
        format.json { render json: @videoformat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videoformats/1
  # PATCH/PUT /videoformats/1.json
  def update
    respond_to do |format|
      if @videoformat.update(videoformat_params)
        format.html { redirect_to @videoformat, notice: 'Videoformat was successfully updated.' }
        format.json { render :show, status: :ok, location: @videoformat }
      else
        format.html { render :edit }
        format.json { render json: @videoformat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videoformats/1
  # DELETE /videoformats/1.json
  def destroy
    @videoformat.destroy
    respond_to do |format|
      format.html { redirect_to videoformats_url, notice: 'Videoformat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_videoformat
      @videoformat = Videoformat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def videoformat_params
      params.require(:videoformat).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = (column == params[:sort] && params[:direction] == "asc") ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/videoformats_helper.rb
module VideoformatsHelper
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" >Raymond Movie Manager</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/welcome/home">Home</a></li>
        <li class="active"> <%= link_to 'New Movie', new_movie_path %> </li>
      </ul>

    </div>
  </div>
</nav>



</body>
</html>




</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RaymondMovieManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="container">
   <div class="col-sm-offset-4">
     <form class="form-horizontal">

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %><br>
    <div class="col-lg-4">
       <%= f.text_field :title, class: "form-control",autofocus: true %>
    </div> <br> <br>
  </div>
     </form>

     <div class="form-group">
    <%= f.label :length, class: "col-sm-2 control-label" %><br>
       <div class="col-sm-4">
    <%= f.time_select :length, class: "form-control",autofocus: true %>
       </div> <br> <br>
  </div>
     <div class="form-group">
    <%= f.label :release, class: "col-sm-2 control-label" %><br>
       <div class="col-sm-4">
    <%= f.number_field :release, class: "form-control",autofocus: true %>
       </div> <br> <br>
  </div>
     <div class="form-group">
    <%= f.label :videoformat_id, class: "col-sm-2 control-label" %><br>
       <div class="col-md-4">
    <%= f.collection_select :videoformat_id, Videoformat.all, :id, :name, class: "form-control",autofocus: true %>
       </div> <br> <br>
  </div>
     <div class="form-group">
    <%= f.label :rating_id, class: "col-sm-2 control-label" %><br>
       <div class="col-sm-4">
    <%= f.collection_select :rating_id, Rating.all, :id, :rate, class: "form-control",autofocus: true %>
     </div> <br> <br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
</form>
</div>
</div>

app/views/movies/edit.html.erb
<h1 class="h">Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie, class: "btn btn-primary" %>
<%= link_to 'Back', movies_path, class: "btn btn-primary" %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="h">Listing Movies</h1>
<%= paginate @movies %>
<%= search_form_for @search do |f| %>
    <div class="field">
      <% f.label :title_cont, "Name contains" %>
      <%= f.text_field :title_cont %>
    </div>
    <div class="actions"><%= f.submit "Search" %></div>
    <% end %>
<div class="form-group">
  <div class="col-sm-4 ">
  </div>
</div> <br> <br>
<table  class="table table-bordered">

  <thead>
    <tr class="info">
      <th class="info"><%= link_to "Title", :sort => "title" %></th>
      <th class="info"><%= link_to "Length", :sort => "length" %></th>
      <th class="info"><%= link_to "Release", :sort => "release" %></th>
      <th class="info"><%= link_to "Videoformat", :sort => "videoformat" %></th>
      <th class="info"><%= link_to "Rating", :sort => "rating" %></th>
      <th colspan="3" col="5" class="info">Options</th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.length %></td>
        <td><%= movie.release %></td>
        <td><%= movie.videoformat.name %></td>
        <td><%= movie.rating.rate if movie.rating %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--%= link_to 'New Movie', new_movie_path, class: "btn btn-default" %> -->

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path, class: "btn btn-default" %>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <h2>Movie Review</h2>
  </div>
</div>
<div>
  <table class="table table-responsive">
    <table class="table">
           <tbody>
           <tr>
             <td><strong>Title:</strong></td>
             <td><%= @movie.title %></td>
           </tr>
           <tr>
           <td><strong>Length:</strong></td>
           <td><%= @movie.length %></td>
           </tr>
           <tr>
             <td> <strong>Release:</strong></td>
             <td><%= @movie.release  %></td>
           </tr>
           <tr>
             <td><strong>Video format:</strong></td>
             <td><%= @movie.videoformat.name %></td>
           </tr>
           <tr>
             <td><strong>Rating:</strong></td>
             <td><%= @movie.rating.rate if @movie.rating %></td>
           </tr>
           </tbody>
    </table>
  </table>
</div>


<%= link_to 'Edit', edit_movie_path(@movie), class: "btn btn-info" %>
<%= link_to 'Back', movies_path, class: "btn btn-info" %>

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rate %><br>
    <%= f.number_field :rate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Rate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating_id %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rate:</strong>
  <%= @rating.rate %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>

app/views/videoformats/_form.html.erb
<%= form_for(@videoformat) do |f| %>
  <% if @videoformat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@videoformat.errors.count, "error") %> prohibited this videoformat from being saved:</h2>

      <ul>
      <% @videoformat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videoformats/edit.html.erb
<h1>Editing Videoformat</h1>

<%= render 'form' %>

<%= link_to 'Show', @videoformat %> |
<%= link_to 'Back', videoformats_path %>

app/views/videoformats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videoformats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videoformats.each do |videoformat| %>
      <tr>
        <td><%= videoformat.name %></td>
        <td><%= link_to 'Show', videoformat %></td>
        <td><%= link_to 'Edit', edit_videoformat_path(videoformat) %></td>
        <td><%= link_to 'Destroy', videoformat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Videoformat', new_videoformat_path %>

app/views/videoformats/new.html.erb
<h1>New Videoformat</h1>

<%= render 'form' %>

<%= link_to 'Back', videoformats_path %>

app/views/videoformats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @videoformat.name %>
</p>

<%= link_to 'Edit', edit_videoformat_path(@videoformat) %> |
<%= link_to 'Back', videoformats_path %>

app/views/welcome/home.html.erb


<h1 class="h">Welcome to the Movie Review!</h1>
<%= link_to movies_path do %>

    <div class="ratio"> <img src="/assets/movie button.png" height="400" width="400"/> </div>
<%end%>
</body>
